learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views

# Template tagging
app_name = 'basic_app'

urlpatterns = [

    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='others')

]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('basic_app/', include('basic_app.urls'))
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render


def index(request):
    context_dict = {'text':'hello world', 'number':100}
    return render(request, 'basic_app/index.html', context=context_dict)


def other(request):
    return render(request, 'basic_app/other.html')


def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'index' %}" class="navbar-brand">BRAND</a></li>
                <li><a href="{% url 'admin:index' %}" class="navbar-link">Admin</a></li>
                <li><a href="{%  url 'basic_app:others' %}" class="navbar-link">Other</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">

        {% block body_block %}

        {% endblock %}

    </div>

</body>
</html>

learning_templates/templates/basic_app/index.html
<!doctype html>
{% extends "basic_app/base.html" %}
    {% block body_block %}
        <h1>Welcome to the index page</h1>
        <h1>{{ text|cut:'world' }}</h1>
        <h1>{{ number|add:'4' }}</h1>
    {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}.
{% block body_block %}
    <h1>Welcome to the other page!</h1>
    <h2>This is an example of template inheritance.</h2>
{% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}
        <h1>Welcome to relative url templates</h1>
        <a href="{% url 'basic_app:others' %}">The Other Page</a> <br>
        <a href="{% url 'admin:index' %}">Link to admin</a><br>

        <a href="{% url 'index' %}">Link to index</a>
    {% endblock %}